### ISSUE TITLE
Change "Back to My Flights" button text to "Save and Return to Flights"

### ISSUE THREAD

**Issue by prphntm63** [CIA-Homebrew/BJCP-Scoresheet#102]
Feature request per Andy Scherzinger - 

This text is a bit more intuitive; it lets the user know their changes will be saved.

Needs to be updated [here](https://github.com/CIA-Homebrew/BJCP-Scoresheet/blob/4a12ee6b90c06882af7eec70dd457e1981dd6b26/views/scoresheet.pug#L71) and [here (for mead)](https://github.com/CIA-Homebrew/BJCP-Scoresheet/blob/4a12ee6b90c06882af7eec70dd457e1981dd6b26/views/scoresheet_mead.pug#L127)

**Comment by Rishav1707** [comment]
Shall I work on this issue?
