### ISSUE TITLE
Long passwords don't work

### ISSUE THREAD

**Issue by prphntm63** [CIA-Homebrew/BJCP-Scoresheet#128]
Per James Gould, "the system doesn't like 30 character passwords"

**Comment by PH-Lazurous** [comment]
Odd ... the Seq DataTypes.STRING is 255 chars and the bcrypt limit is 71 so that shouldn't be an issue, although we should match that up for consistency regardless. 

Definitely will have to bench that one to figure it out more.

**Comment by prphntm63** [comment]
Yeah it *should* work, but I'm just reporting what I was told, lol.

**Comment by prphntm63** [comment]
This is the password he tried to register with: `TKUqzZmFzyPM0yd88qu3CEtzgn318j`

**Comment by prphntm63** [comment]
I can't reproduce this. Every password I've tried (up to 50 characters) has worked.
