### ISSUE TITLE
Updating scoresheet metadata (place, BOS, etc.) in admin panel overwrites judge

### ISSUE THREAD

**Issue by prphntm63** [CIA-Homebrew/BJCP-Scoresheet#135]
Reported by Javi

* In admin panel - if you set scoresheet metadata as an admin, the scoresheet "user" will be set to the admin account.
* This is due to [this line in this function](https://github.com/CIA-Homebrew/BJCP-Scoresheet/blob/486490b1f86f339b66b09977bffd9d8f773a334d/controllers/ScoresheetController.js#L148) being repurposed by the admin function
* Short term solution - need to add flag to prevent overwriting user
* Branch has already been created, tested, and merged on separate deploy fork - see attached files
  * [BJCP-Scoresheet\controllers\ScoresheetController.js](https://github.com/CIA-Homebrew/BJCP-Scoresheet/files/5828375/ScoresheetController.js.txt)
  * [BJCP-Scoresheet\public\javascripts\admin.js](https://github.com/CIA-Homebrew/BJCP-Scoresheet/files/5828380/admin.js.txt)
* Long term solution - user ID is not needed in scoresheets table, as it references flight ID which is bound to the userID

**Comment by PH-Lazurous** [comment]
We also should add in a change table for tracking purposes. Simple date, user ID, and the serialized data or a clone of the scoresheet table with retention for abilities of look up and roll backs as needed.

**Comment by prphntm63** [comment]
Not a bad idea. For now, we could just add a "record" json field and keep track of any changes in the entry itself.
