### ISSUE TITLE
Ability for admins / users to delete scoresheets

### ISSUE THREAD

**Issue by prphntm63** [CIA-Homebrew/BJCP-Scoresheet#137]
Sometimes, users accidentally create extra scoresheets. Having a delete functionality is critical

Front End Requirements:
* Can only delete scoresheets on in-progress flights
* Delete confirmation
* Admins should be able to recover soft-deleted scoresheets from admin panel

Back End Requirements:
* Soft delete - scoresheets are flagged as 'deleted' for 24 hours before permanent db removal
* Users should be blocked from deleting scoresheets they did not create

**Comment by PH-Lazurous** [comment]
duplicate/elaboration of #34
