### ISSUE TITLE
Ability for admins / users to delete empty flights

### ISSUE THREAD

**Issue by prphntm63** [CIA-Homebrew/BJCP-Scoresheet#138]
Sometimes, users accidentally create extra flights. Having a delete functionality is critical to app flow and self-service.

Front End Requirements:
* Can only delete flights with no scoresheets
* Delete confirmation

Back End Requirements:
* Users should be blocked from deleting flights they did not create

**Comment by PH-Lazurous** [comment]
duplicate/elaboration of #34
