### ISSUE TITLE
Figure out a way to repopulate scoresheet from 'half-done' form

### ISSUE THREAD

**Issue by prphntm63** [CIA-Homebrew/BJCP-Scoresheet#6]
Main issue - should we have a separate 'load' page or try to re-use the 'new' page but have default values? 

re-using 'new' page would make updating easier, but a 'load' page would be easier to make one off. I'm leaning toward not screwing future matt so maybe I'll look into adding optional pre-filled values on the new page.

**Comment by PH-Lazurous** [comment]
Should be simple enough to just test if the value of the 'sheet' object exists else load a default. Similar to the profile page would be my thoughts.
