### ISSUE TITLE
Remove redundant Scoresheet fields for judge information (dependency on #85)

### ISSUE THREAD

**Issue by PH-Lazurous** [CIA-Homebrew/BJCP-Scoresheet#64]
Inputs marked as disabled are not sending data in the ajax data save. Changing to readonly fixes this, will be fixed in upcoming commit.

**Comment by prphntm63** [comment]
Are you talking about location, date, judge info, etc? Those should be pulled from flight / user tables and _technically_ not saved to the scoresheet db as it violates the ideal relational model structure.

**Comment by prphntm63** [comment]
Not saying we shouldn't fix this fields, but not writing these values in the scoresheet db entry shouldn't be breaking anything.

**Comment by PH-Lazurous** [comment]
They are pulled from the flight table correct, and the auto populate works. However in my testing it was not persisting past the initial creation of the scoresheet. Maybe it was a break in a path on my URL reformats, let me double check that.

**Comment by PH-Lazurous** [comment]
Also if we are not going to store that data in the scoresheet directly there is no reason creating those extra fields in the db/model that just remain blank. That's where the reference / joins should be exposing that data in the model.

**Comment by prphntm63** [comment]
I agree. The resolution should be making a migration to remove the redundant fields and/or fixing the stupid sequelize joins (#14 ) lol
