### ISSUE TITLE
"Cicerone" is always checked on scoresheet, even if user is not a cicerone

### ISSUE THREAD

**Issue by prphntm63** [CIA-Homebrew/BJCP-Scoresheet#75]
When generating a pdf scoresheet, the "cicerone" box is always checked and "N/A" is displayed in the field even if the user is not a cicerone.
![cicerone](https://user-images.githubusercontent.com/4017530/98482151-0ae53700-21c5-11eb-92cd-f89f7efb4f75.PNG)

**Comment by PH-Lazurous** [comment]
#81
