### ISSUE TITLE
Show actual calculated SRM color range on appearance tab

### ISSUE THREAD

**Issue by prphntm63** [CIA-Homebrew/BJCP-Scoresheet#79]
On appearance tab - show the SRM colors on the color range slider, and/or preview the BJCP SRM acceptable range

Objectives:
1. Set the text color of the labels on the 'color' slider to be equivalent to their names
     * [Color table here](https://brookstonbeerbulletin.com/thinking-about-beer-color/)
2. Add color blocks to "Style Guidelines" tooltip showing acceptable BJCP range

**Comment by PH-Lazurous** [comment]
would probably be best for a full color range vs BJCP accepted that way if it's out of style you can define that in the scoresheet still. 

Old XMKL lookup table I had saved from a while back ... https://www.barleydogbrewery.com/xml/colors.xml

**Comment by prphntm63** [comment]
Agreed. I previously wrote a JS function that converts SRM to RGB as well 
[srmToRgb.js.txt](https://github.com/CIA-Homebrew/BJCP-Scoresheet/files/5515188/srmToRgb.js.txt)

**Comment by PH-Lazurous** [comment]
So thinking about this one a bit, with all the specialty beers starting to find categories would this be best to have a full color palette to manually pick and the 'traditional' beer colors as quick selectors? Seeing more and more beers (mainly from fruit additions) that are pink, green, blue, etc. etc. so just thought about it. 

Quick example

`23F. Fruit Lambic
....
Appearance: **_The variety of fruit generally determines the
color,_** although lighter-colored fruit may have little effect on
the color. The color intensity may fade with age. Clarity is often
good, although some fruit will not drop bright. A thick rocky,
mousse-like head, sometimes a shade of fruit, is generally longlasting (carbonation-dependent). Carbonation is typically high,
but must be specified.
....`

**Comment by prphntm63** [comment]
This ties in with #127

**Comment by prphntm63** [comment]
But what I was doing during judging was putting a comment with odd colors. For example, a cherry lambic, I'd mark the color as "gold" with a comment that said "Dark ruby red tint"

**Comment by prphntm63** [comment]
For cider and mead (#147 ) we may want to add a more "versatile" color picker

**Comment by prphntm63** [comment]
Implemented with #197
