### ISSUE TITLE
Double quotes in text fields prevent JSON parsing when editing scoresheet

### ISSUE THREAD

**Issue by prphntm63** [CIA-Homebrew/BJCP-Scoresheet#89]
Double quotes in block text need to be escaped before sending data.

Heck, the whole thing should be sanitized before sending.

**Comment by PH-Lazurous** [comment]
(going off memory) Sequelize at a minimum escapes all strings to help with things like this, but there is an additional layer we can add that would sanitize even further. I'll have to do a bit of digging on this just to double check but that was what I remembered. However I do not think we are doing anything in the update routine on the client side besides creating a JSON string and then posting to the backend, not sure if that is where we are having the break in things as well.

**Comment by prphntm63** [comment]
It's a stupid issue based quote escaping purely due to how we load the object data into the script in the pug template. We should revisit this and do it properly - with a POST fetch. Lol.
